<a href="https://colab.research.google.com/github/ZeroJoon2/DeepLearning/blob/main/3_%EA%B7%B8%EB%9E%98%EB%94%94%EC%96%B8%ED%8A%B8_%ED%85%8C%EC%9D%B4%ED%94%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

#1. scala 값의 기울기 계산

x = tf.Variable(0.)

with tf.GradientTape() as tape:
    # y를 계산하기 위한 규칙
    y = 2*x + 3

grad_y_x = tape.gradient(y, x)
grad_y_x

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [5]:
# 2. 행렬의 기울기 계산

x = tf.Variable(tf.zeros((2,2)))
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [7]:
with tf.GradientTape() as tape:
    y = 2*x + 3
grad_y_x = tape.gradient(y, x) # y에 대해 x로 미분\
grad_y_x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [13]:
#3. 선형함수의 기울기 w 계산

# 가중치 = 기울기
W = tf.Variable(tf.random.uniform((2,2)))
b = tf.Variable(tf.zeros((2,)))

x = tf.random.uniform((2,2))
print(f'''
▶ x
{x}

▶ W
{W}

▶ b
{b}

''')

with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b # w*x



x
[[0.81836414 0.5578401 ]
 [0.6280856  0.50057924]]
      
W
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.7292911 , 0.3586378 ],
       [0.46556795, 0.8687873 ]], dtype=float32)>
      
b
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>


